name: CI/CD for Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-tests:
    name: Run Tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN_TUTORIAL_TEMP }}
          fetch-depth: 0

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd app
          python3 -m pytest ../tests/